version: '3.8'

services:
  iphish-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iphish-frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginxs.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      iphish-net:
        ipv4_address: 172.22.0.12

networks:
  iphish-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16